---
- name: Manage OpenStack Servers
  hosts: control_node
  gather_facts: false
  become: false
  collections:
    - gpte.openstack

  roles:

    - openstack_manage_servers

- import_playbook: update_dns.yml
- import_playbook: patch_servers.yml

...
